services:

  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./pyload-ng/config:/config
      - ./pyload-ng/downloads:/downloads
    ports:
      - "8200:8000"
      - "9666:9666"
    restart: unless-stopped